### ISSUE TITLE
Investigate vignette error in load_data()

### ISSUE THREAD

**Issue by davidearthur** [Avi-Kenny/steppedwedge#7]
On the GitHub vignette, there is an error in the first chunk that doesn't occur when I run or knit steppedwedge.Rmd on my computer.
![image](https://github.com/user-attachments/assets/0ef0217c-3f27-4a37-a955-479a53777ece)

**Comment by Avi-Kenny** [comment]
This was *nasty* to debug. The issue seems to be with several `dplyr` functions in combination with `pkgdown`. I found a workaround by essentially including the `load_data()` call twice in the vignette code, once in a `{r, include = FALSE}` block. For whatever reason, the error is only thrown the first time and subsequent calls are fine. So for now, this appears to be resolved.
